name: SkyWars-Core
author: AEndrix
description: SkyWars
version: 1.0.2
main: it.aendrix.skywars.main.Main
softdepend: [Multiverse-Core]

commands:
    skywars:
        aliases: [sw]
        description: Skywars main command
        default: OP